# Generated by Django 4.1.7 on 2023-04-29 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_blog_video_alter_blog_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(default='blog.id', on_delete=django.db.models.deletion.CASCADE, to='home.blog'),
        ),
    ]
